
    import pandas as pd
    from pycaret.MLUsecase.CLASSIFICATION import load_model, predict_model
    from fastapi import FastAPI
    import uvicorn
    # Create the app
    app = FastAPI()
    # Load trained Pipeline
    model = load_model('pycaret/selectImportance/pycaret_api')
    # Define predict function
    @app.post('/predict')
    def predict(PAYMENT_RATE, EXT_SOURCE_1, EXT_SOURCE_3, EXT_SOURCE_2, DAYS_BIRTH, AMT_ANNUITY, DAYS_EMPLOYED, DAYS_ID_PUBLISH, APPROVED_CNT_PAYMENT_MEAN, DAYS_EMPLOYED_PERC, INCOME_CREDIT_PERC, INSTAL_DAYS_ENTRY_PAYMENT_MAX, ACTIVE_DAYS_CREDIT_MAX, DAYS_REGISTRATION, ACTIVE_DAYS_CREDIT_ENDDATE_MIN, AMT_CREDIT, REGION_POPULATION_RELATIVE, INSTAL_DPD_MEAN, AMT_GOODS_PRICE, PREV_CNT_PAYMENT_MEAN):
        data = pd.DataFrame([[PAYMENT_RATE, EXT_SOURCE_1, EXT_SOURCE_3, EXT_SOURCE_2, DAYS_BIRTH, AMT_ANNUITY, DAYS_EMPLOYED, DAYS_ID_PUBLISH, APPROVED_CNT_PAYMENT_MEAN, DAYS_EMPLOYED_PERC, INCOME_CREDIT_PERC, INSTAL_DAYS_ENTRY_PAYMENT_MAX, ACTIVE_DAYS_CREDIT_MAX, DAYS_REGISTRATION, ACTIVE_DAYS_CREDIT_ENDDATE_MIN, AMT_CREDIT, REGION_POPULATION_RELATIVE, INSTAL_DPD_MEAN, AMT_GOODS_PRICE, PREV_CNT_PAYMENT_MEAN]])
        data.columns = ['PAYMENT_RATE', 'EXT_SOURCE_1', 'EXT_SOURCE_3', 'EXT_SOURCE_2', 'DAYS_BIRTH', 'AMT_ANNUITY', 'DAYS_EMPLOYED', 'DAYS_ID_PUBLISH', 'APPROVED_CNT_PAYMENT_MEAN', 'DAYS_EMPLOYED_PERC', 'INCOME_CREDIT_PERC', 'INSTAL_DAYS_ENTRY_PAYMENT_MAX', 'ACTIVE_DAYS_CREDIT_MAX', 'DAYS_REGISTRATION', 'ACTIVE_DAYS_CREDIT_ENDDATE_MIN', 'AMT_CREDIT', 'REGION_POPULATION_RELATIVE', 'INSTAL_DPD_MEAN', 'AMT_GOODS_PRICE', 'PREV_CNT_PAYMENT_MEAN']
        predictions = predict_model(model, data=data)
        return {'prediction': list(predictions['Label'])}
    if __name__ == '__main__':
        uvicorn.run(app, host='127.0.0.1', port=8000)